### PR TITLE
Dev 105 update deps add dep check

### PR DESCRIPTION
**Pull request by rikuhaa**
Add vulnerability check profile, and update some dependencies
I did a quick test with the updated dependencies with Scroll ImageMap and Scroll Documents - the main thing that could have problems is the iframe resizing (there was a major version bump that should not break anything else than support to some old browsers). In my quick testing I did not see any problems

### CODE REVIEW

**Review by jensrutschmann — COMMENTED** [review]
According to the changelog they had renamed their callbacks in version 4.0.0.
See https://github.com/davidjbradshaw/iframe-resizer/commit/2387294ba16f9d4828960da16518d540ed68a2c8#diff-c21cf257da2c6a66ea81fad0fab72190R61

Yet we still use the `resizedCallback `in a test in
https://github.com/K15t/spark/blob/DEV-105-update-deps-add-dep-check/spark-common/src/main/js/test/specs/iframeAppLoaderSpec.js#L418

Doesn't this mean we need to adapt the test as well?

**Comment by rikuhaa** [comment]
> According to the changelog they had renamed their callbacks in version 4.0.0.
> See [davidjbradshaw/iframe-resizer@2387294#diff-c21cf257da2c6a66ea81fad0fab72190R61](https://github.com/davidjbradshaw/iframe-resizer/commit/2387294ba16f9d4828960da16518d540ed68a2c8#diff-c21cf257da2c6a66ea81fad0fab72190R61)
> 
> Yet we still use the `resizedCallback `in a test in
> https://github.com/K15t/spark/blob/DEV-105-update-deps-add-dep-check/spark-common/src/main/js/test/specs/iframeAppLoaderSpec.js#L418
> 
> Doesn't this mean we need to adapt the test as well?

Have to check that - I read the release notes but forgot the callback renaming
The test seems to still work, maybe the test itself does not do too much...
At least we should check if the apps are using the callbacks for something (I guess it might be unlikely)

**Comment by rikuhaa** [comment]
I updated the resizeCallback -> onResized
I also found out that the '*callbac' also still works, it will just log a warning

At least in Documents the 'resizeCallback' is overridden, so the override should be renamed too there

**Review by jensrutschmann — APPROVED** [review]

**Review by Moerphy — APPROVED** [review]

**Comment by rikuhaa** [comment]
@jensrutschmann @Moerphy pushed one more commit based on a suggestion from Jens (I tested it, it works, and I think it is a good sanity check even if the case maybe could not have happened in practice)

ready to be merged for my part but maybe you want to check the last commit first

**Review by jensrutschmann — APPROVED** [review]

**Pull request merged**
